'use strict';(function(){var cmpFile='noModule'in HTMLScriptElement.prototype?'cmp2.js':'cmp2-polyfilled.js';(function(){var cmpScriptElement=document.createElement('script');var firstScript=document.getElementsByTagName('script')[0];cmpScriptElement.async=true;cmpScriptElement.type='text/javascript';var cmpUrl;var tagUrl=document.currentScript.src;cmpUrl='https://cmp.inmobi.com/tcfv2/53/CMP_FILE?referer=www.themoneytizer.com'.replace('CMP_FILE',cmpFile);cmpScriptElement.src=cmpUrl;firstScript.parentNode.insertBefore(cmpScriptElement,firstScript);})();(function(){var css=""
+" .qc-cmp-button.qc-cmp-secondary-button:hover { "
+"   background-color: #368bd6 !important; "
+"   border-color: transparent !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button:hover { "
+"   color: #ffffff !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button { "
+"   color: #368bd6 !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button { "
+"   background-color: #eee !important; "
+"   border-color: transparent !important; "
+" } "
+""
+"";var stylesElement=document.createElement('style');var re=new RegExp('&quote;','g');css=css.replace(re,'"');stylesElement.type='text/css';if(stylesElement.styleSheet){stylesElement.styleSheet.cssText=css;}else{stylesElement.appendChild(document.createTextNode(css));}
var head=document.head||document.getElementsByTagName('head')[0];head.appendChild(stylesElement);})();var autoDetectedLanguage='en';var gvlVersion=3;function splitLang(lang){if(lang.includes('pt')&&lang.length>2){return lang.split('-')[0]+'-'+lang.split('-')[1].toLowerCase();}
return lang.length>2?lang.split('-')[0]:lang;};function isSupported(lang){var langs=['en','fr','de','it','es','da','nl','el','hu','pt','pt-br','pt-pt','ro','fi','pl','sk','sv','no','ru','bg','ca','cs','et','hr','lt','lv','mt','sl','tr','uk','zh','id','ko','ja','hi','vi','th','ms'];return langs.indexOf(lang)===-1?false:true;};if(gvlVersion===2&&isSupported(splitLang(document.documentElement.lang))){autoDetectedLanguage=splitLang(document.documentElement.lang);}else if(gvlVersion===3&&isSupported(document.documentElement.lang)){autoDetectedLanguage=document.documentElement.lang;}else if(isSupported(splitLang(navigator.language))){autoDetectedLanguage=splitLang(navigator.language);};var choiceMilliSeconds=(new Date).getTime();window.__tcfapi('init',2,function(){},{"coreConfig":{"uspVersion":1,"uspJurisdiction":["CA"],"uspLspact":"N","siteUuid":"e5ccf1a5-771a-4e03-918b-4436cd01e60d","themeUuid":"041f0fd5-d900-4fc9-89ed-1cee3b6df39e","suppressCcpaLinks":true,"inmobiAccountId":"6Fv0cGNfc_bw8","privacyMode":["GDPR","USP"],"includeVendorsDisclosedSegment":false,"cmpVersion":"53","hashCode":"6fGBLJ3kXEJ9oZClmKqFdQ","publisherCountryCode":"US","publisherName":"themoneytizer.com","vendorPurposeIds":[2,4,6,7,9,10,1,3,5,8,11],"vendorFeaturesIds":[1,2,3],"vendorPurposeLegitimateInterestIds":[7,8,9,2,10,11],"vendorSpecialFeaturesIds":[2,1],"vendorSpecialPurposesIds":[1,2],"googleEnabled":true,"consentScope":"service","thirdPartyStorageType":"iframe","consentOnSafari":false,"displayUi":"inEU","defaultToggleValue":"off","initScreenRejectButtonShowing":false,"initScreenCloseButtonShowing":false,"softOptInEnabled":false,"showSummaryView":true,"persistentConsentLinkLocation":3,"displayPersistentConsentLink":true,"uiLayout":"banner","vendorListUpdateFreq":30,"publisherPurposeIds":[],"initScreenBodyTextOption":1,"publisherConsentRestrictionIds":[],"publisherLIRestrictionIds":[],"stacks":[1,42],"lang_":autoDetectedLanguage,"gvlVersion":3,"totalVendors":876,"gbcConfig":{"enabled":true,"urlPassThrough":null,"adsDataRedaction":null,"locations":["EEA"],"applicablePurposes":[{"id":1,"defaultValue":"GRANTED"},{"id":2,"defaultValue":"GRANTED"},{"id":3,"defaultValue":"GRANTED"},{"id":4,"defaultValue":"GRANTED"},{"id":5,"defaultValue":"GRANTED"},{"id":6,"defaultValue":"GRANTED"},{"id":7,"defaultValue":"GRANTED"}]},"legitimateInterestOptIn":true,"features":{"visitEvents":true},"translationUrls":{"common":"https://cmp.inmobi.com/tcfv2/translations/${language}.json","theme":"https://cmp.inmobi.com/custom-translations/6Fv0cGNfc_bw8/041f0fd5-d900-4fc9-89ed-1cee3b6df39e/${language}.json","all":"https://cmp.inmobi.com/consolidated-translations/6Fv0cGNfc_bw8/041f0fd5-d900-4fc9-89ed-1cee3b6df39e/${language}.json"},"gdprEnabledInUS":false},"premiumUiLabels":{"uspDnsText":[""]},"premiumProperties":{"googleWhitelist":[1]},"coreUiLabels":{},"theme":{},"nonIabVendorsInfo":{}});})();